sudo: required

language: node_js
node_js: lts/*

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test -- --single-run

after_success:
    - npm run build:unix

deploy:
  - provider: pages
    skip-cleanup: true
    local-dir: dist
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
  - provider: npm
      email: $NPM_EMAIL
      api_key: $NPM_TOKEN
